eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765

feign:
  hystrix:
    enabled: true

hystrix:
  metrics:
    enabled: true

spring:
  application:
    name: feign-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: ["health","info","bus-refresh"]
