application:
  version: 1.1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763

spring:
  application:
    name: service-hello-world
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: ["health","info","bus-refresh"]
spring:
  zipkin:
    service:
      name: zipkin-server
