eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-peer1:8761/eureka/,http://eureka-server-peer2:8762/eureka/,http://eureka-server-peer3:8759/eureka/

server:
  port: 8769

spring:
  application:
    name: zuul-routing
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    sender:
      type: web
    base-url: http://localhost:8770
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0

zuul:
  routes:
    api-ribbon:
      path: /api-ribbon/**
      serviceId: ribbon-consumer
    api-feign:
      path: /api-feign/**
      serviceId: feign-consumer
management:
  endpoints:
    web:
      exposure:
        include: ["health","info","bus-refresh"]
