server:
  port: 8760
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:killer9527/LearnSpringCloud.git
          search-paths: wfw-config-repo
          clone-on-start: true
          force-pull: true
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-peer1:8761/eureka/,http://eureka-server-peer2:8762/eureka/,http://eureka-server-peer3:8759/eureka/
