spring:
  application:
    name: eureka-server
  profiles: peer2

server:
  port: 8762

eureka:
  instance:
# 需修改本机C:\Windows\System32\drivers\etc\hosts文件，添加 127.0.0.1       eureka-server-peer2
    hostname: eureka-server-peer2
  client:
#通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server-peer1:8761/eureka/,http://eureka-server-peer3:8759/eureka/

